# Footnotes

## Setup of Apache Arrow

It is worth noting that the implementation of Apache Arrow [into R](https://github.com/apache/arrow/tree/master/r) arrived on [CRAN](https://cran.r-project.org/package=arrow) early August 2019, which means at the time of writing of the relevant chapter it was on CRAN about 3 weeks. The functionality also depends on the [Arrow C++ library](https://arrow.apache.org/install/), so installation is a bit more difficult than with some other R packages. 

Care should also be taken with regards to the capability of the C++ library, the arrow R package version and the version of sparklyr. We had good results with using the R package arrow version 0.14.1, sparklyr 1.0.2 and the 0.14.1 version of the C++ libraries.
Care should also be taken with regards to the capability of the C++ library, the arrow R package version and the version of sparklyr. We had good results with using the R package arrow version 0.14.1, sparklyr 1.0.2 and the 0.14.1 version of the C++ libraries.

The aforementioned [Docker image](https://hub.docker.com/repository/docker/jozefhajnala/sparkfromr) has both the C++ libraries and the R arrow package available for use.
