name: deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Render Book
      run: sh build/sparkfromr_render_test.sh
    - name: Deploy site
      if: github.ref == 'refs/heads/master'
      env:
        SPARKFROMR_DEPLOYED_GH_TOKEN: ${{ secrets.SPARKFROMR_DEPLOYED_GH_TOKEN }}
      run: |
        echo Deploying site
        sh build/sparkfromr_auto_deploy.sh
